# Generated by Django 4.1.7 on 2023-03-11 10:41

import django.core.validators
from django.db import migrations, models
import sahan.clips.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                        verbose_name="name",
                    ),
                ),
                (
                    "ident",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                        verbose_name="ident",
                    ),
                ),
                ("keywords", models.TextField(verbose_name="keywords")),
                (
                    "file",
                    models.FileField(
                        upload_to=sahan.clips.models.clipdir,
                        verbose_name="file",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
            ],
            options={
                "verbose_name": "clip",
                "verbose_name_plural": "clips",
            },
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(
                fields=["is_active"], name="clips_clip_is_acti_64d33d_idx"
            ),
        ),
    ]
